name: 5-Pencil Method
favicon: null
layout_spectrum: 0.6217414708808064
typography_spectrum: 0.9095987579785287
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.10893813474103808
  lightness: 0.30314551829360425
  saturation: 0.4837698074989021
  rhythmicContrast: 0.3600144782103598
purpose: []
