name: 5-Pencil Method
favicon: null
layout_spectrum: 0
typography_spectrum: 0.36806
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#792d47'
    - '#e3e4e1'
    - '#1a1919'
    - '#a3a5a2'
    - '#6b6d6a'
  brandStrength: 0.5
  lightness: 0.6875
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
